// scrapers/beturi_ro.js
// Custom scraper for beturi.ro using WP REST + strict Flashscore resolver via matches.json
// Requires: matches.json already generated by scrape_mobi.js
// Output: array of selections with mandatory match_id

import fs from "fs/promises";
import fetch from "node-fetch";
import * as cheerio from "cheerio";

const SOURCE = "beturi";
const BETURI_WP_API = "https://beturi.ro/wp-json/wp/v2/posts";

// -------- utils --------
const norm = (s = "") =>
  String(s)
    .toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/&amp;/g, "&")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim();

function buildTargetDate(dayOffset = 0) {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return { yyyy, mm, dd, ddmmyyyy_dots: `${dd}.${mm}.${yyyy}`, ddmmyyyy_dashes: `${dd}-${mm}-${yyyy}` };
}

function parseTeamsFromTitle(h1 = "") {
  // Example: "Brighton – Bournemouth – Ponturi Premier League – 19.01.2026"
  const cleaned = h1.replace(/\s+/g, " ").trim();
  // split by dash variants
  const parts = cleaned.split(/–|—|-/).map(x => x.trim()).filter(Boolean);
  if (parts.length < 2) return null;
  return { home: parts[0], away: parts[1] };
}

function parsePickAndOdd($) {
  // beturi pages often have a short pick line + odd near top:
  // e.g. "Ambele marchează" then "1.50"
  // We'll take first strong line that looks like a pick, then nearest odd.
  const bodyText = $("body").text().replace(/\s+/g, " ").trim();

  // pick candidates (short-ish lines in rendered content area)
  let pick = null;
  // Try: find the first line between title and "Joaca la"
  const idxPlay = bodyText.toLowerCase().indexOf("joaca la");
  const window = (idxPlay > 0 ? bodyText.slice(0, idxPlay) : bodyText).slice(0, 600);

  // Common picks in RO
  const pickMatchers = [
    /ambele marcheaz[aă]/i,
    /minim\s+\d+\s+goluri/i,
    /peste\s+\d+(\.\d+)?/i,
    /sub\s+\d+(\.\d+)?/i,
    /\b1x\b/i, /\bx2\b/i, /\b12\b/i,
    /\bvictorie\b/i, /\begal\b/i
  ];
  for (const re of pickMatchers) {
    const m = window.match(re);
    if (m) { pick = m[0]; break; }
  }
  // fallback: try first <h2>/<strong> short text
  if (!pick) {
    const cand = $("h2,strong").first().text().trim();
    if (cand && cand.length < 60) pick = cand;
  }
  if (!pick) return { pickText: null, odd: null };

  // odd: take first decimal like 1.50 / 2.05 close to pick
  // (avoid years etc by requiring 1.xx–9.xx)
  const oddMatch = window.match(/\b([1-9]\d?\.\d{2})\b/);
  const odd = oddMatch ? Number(oddMatch[1]) : null;

  return { pickText: pick, odd };
}

function parseKickoffTime($) {
  // beturi shows: "22:00 - Voyo" or "01:30"
  const text = $("body").text().replace(/\s+/g, " ").trim();
  const m = text.match(/\b(\d{1,2}:\d{2})\b/);
  return m ? m[1] : null;
}

function strictResolveMatchId(matches, home, away, timeStr) {
  const nh = norm(home);
  const na = norm(away);
  const targetTime = timeStr || "";

  const candidates = matches.filter(m => {
    const mt = norm(m.teams || "");
    if (!mt) return false;
    // require both team names present
    return mt.includes(nh) && mt.includes(na);
  });

  if (!candidates.length) return null;

  // if time is available, narrow down by exact time OR within 2 hours
  if (targetTime && /^\d{1,2}:\d{2}$/.test(targetTime)) {
    const toMin = (hhmm) => {
      const [h, mi] = hhmm.split(":").map(Number);
      return h * 60 + mi;
    };
    const t0 = toMin(targetTime);

    const byTime = candidates.filter(c => {
      if (!c.time || !/^\d{1,2}:\d{2}$/.test(c.time)) return true; // don't exclude if missing
      const tc = toMin(c.time);
      const diff = Math.abs(tc - t0);
      return diff <= 120; // 2h tolerance (timezone/feed differences)
    });

    if (byTime.length === 1) return byTime[0].id;
    if (byTime.length > 1) {
      // try exact match
      const exact = byTime.filter(c => c.time === targetTime);
      if (exact.length === 1) return exact[0].id;
      return null; // ambiguous
    }
    return null;
  }

  // if no time, only accept if exactly one candidate
  return candidates.length === 1 ? candidates[0].id : null;
}

// -------- main scrape --------
export async function scrapeBeturi({ dayOffset = 0, maxPosts = 30 } = {}) {
  // 1) load flashscore fixtures
  const matchesRaw = await fs.readFile("matches.json", "utf8");
  const matches = (JSON.parse(matchesRaw).matches || []);

  const { ddmmyyyy_dots } = buildTargetDate(dayOffset);

  // 2) find beturi posts for that date (they include date in title, like 19.01.2026)
  const url = `${BETURI_WP_API}?per_page=${maxPosts}&orderby=date&order=desc&search=${encodeURIComponent(ddmmyyyy_dots)}&_fields=id,link,title,content,date`;
  const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0" } });
  if (!res.ok) {
    console.log(`[beturi] WP API failed: HTTP ${res.status}`);
    return [];
  }
  const posts = await res.json();
  console.log(`[beturi] found ${posts.length} posts for ${ddmmyyyy_dots}`);

  const out = [];
  for (const p of posts) {
    const html = p?.content?.rendered || "";
    if (!html) continue;
    const $ = cheerio.load(html);

    const h1 = (p?.title?.rendered || "").replace(/<[^>]+>/g, "").trim();
    const teams = parseTeamsFromTitle(h1);
    if (!teams) continue;

    const kickoff = parseKickoffTime($); // HH:MM
    const { pickText, odd } = parsePickAndOdd($);
    if (!pickText || !odd) continue;

    const matchId = strictResolveMatchId(matches, teams.home, teams.away, kickoff);
    if (!matchId) {
      // strict rule: discard if not uniquely resolvable
      continue;
    }

    out.push({
      source: SOURCE,
      match_id: matchId,
      flashscore_url: `https://www.flashscore.mobi/match/${matchId}/?s=1&d=${dayOffset}`,
      teams: `${teams.home} – ${teams.away}`,
      time: kickoff || "",
      country: "",        // optional (can be filled later from matches.json if needed)
      competition: "",    // optional
      bet_text_ro: pickText,
      odd,
      post_url: p.link,
      post_date: p.date,
    });
  }

  console.log(`[beturi] resolved ${out.length} picks with strict match_id`);
  return out;
}
