name: Scrape Flashscore mobi

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"  # 07:30 Europe/Bucharest ≈ 04:30 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      - name: Run scraper (football, d=1)
        # setează DAY_OFFSET aici (0=today, 1=tomorrow)
        run: node scrape_mobi.js
        env:
          DAY_OFFSET: "1"
          MAX_MATCHES: "60"

      - name: Upload JSONs
        uses: actions/upload-artifact@v4
        with:
          name: json-output
          path: |
            matches.json
            odds.json

      - name: Upload debug HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-html
          path: |
            list.html
            match-*.html
