name: Flashscore Scraper

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      flash_url:
        description: "URL Flashscore (ex: https://www.flashscore.com/football/italy/serie-a/)"
        required: false
      max_matches:
        description: "Limită meciuri pentru test (ex: 5)"
        required: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          FLASH_URL: ${{ github.event.inputs.flash_url || 'https://www.flashscore.com/football/' }}
          MAX_MATCHES: ${{ github.event.inputs.max_matches || '12' }}
          HEADLESS: "true"
          GUARD_TIME: "1"
        run: npm run scrape

      - name: Upload odds.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: odds-json
          path: odds.json
