name: Scrape Flashscore mobi + Odds + Tickets + WordPress

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"  # 07:30 Europe/Bucharest (04:30 UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      # Scraper controls
      DAY_OFFSET: "0"           # 0=azi, 1=maine
      MAX_MATCHES: "60"
      CONCURRENCY: "6"
      FETCH_TIMEOUT_MS: "12000"
      RETRIES: "1"
      GLOBAL_HARD_STOP_MS: "150000"
      INCLUDE_LIVE: "false"

      # Ticket tolerances (folosite de generate_tickets.js)
      COTA2_TOL: "0.15"
      ZI_TOL: "0.30"

      # The Odds API (optional; dacă lipsesc, scripturile scriu odds_debug.json cu mesaj)
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      ODDS_REGION: "eu"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache npm dir
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-scraper
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install minimal deps
        run: |
          npm install cheerio@^1.0.0-rc.12 node-fetch@^3 --no-fund --no-audit --prefer-offline

      # 1) Fixtures din Flashscore (mobi)
      - name: Run scraper (fixtures - football)
        timeout-minutes: 5
        run: node scrape_mobi.js

      # 2) (Optional) Odds din tab-ul Flashscore ?s=5 (poate fi gol pe unele zile/ligi)
      - name: Run scraper (Flashscore Odds tab)
        timeout-minutes: 5
        run: node scrape_odds_tab.js

      # 3) (Optional) Merge The Odds API (h2h + totals) — sigur de rulat și fără cheie
      - name: Merge (optional) The Odds API odds
        timeout-minutes: 5
        run: |
          if [ -f "scrape_odds_combo.js" ]; then
            node scrape_odds_combo.js
          else
            echo "scrape_odds_combo.js not present, skipping."
          fi

      # 4) Generează biletele din datele curente (fără piețe extra încă)
      - name: Generate tickets (initial)
        run: node generate_tickets.js

      # 5) Augmentează DOAR meciurile selectate cu piețe extra (BetExplorer per-match)
      - name: Augment odds for selected events (BetExplorer per-match)
        run: |
          if [ -f "augment_odds_selected.js" ]; then
            node augment_odds_selected.js
          else
            echo "augment_odds_selected.js not present, skipping."
          fi

      # 6) Re-generează biletele ținând cont de odds_extra.json (DC / O-U etc.)
      - name: Generate tickets (with extras)
        run: node generate_tickets.js

      # 7) Generează HTML pentru WordPress
      - name: Generate WordPress HTML
        run: node generate_wp.js

      # 8) Upload raw artifacts (debug)
      - name: Upload artifacts (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            list.html
            list-odds.html
            match-*.html
            matches.json
            odds.json
            odds_tab.json
            odds_extra.json
            odds_debug.json

      # 9) Upload ticket outputs
      - name: Upload artifacts (tickets)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tickets
          path: |
            tickets.json
            tickets.md
            cota2.html
            biletul-zilei.html

      # 10) Publică în WordPress
      - name: Publish posts to WordPress
        if: success()
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASS: ${{ secrets.WP_APP_PASS }}
        run: node publish_wp.js
